Repository onnx/models, pull requests merged in 2020-07, with the labels that each got.

#322 Add YOLOv4
  README.md
  vision/object_detection_segmentation/yolov4/README.md
  vision/object_detection_segmentation/yolov4/dependencies/Conversion.ipynb
  vision/object_detection_segmentation/yolov4/dependencies/inference.ipynb
  vision/object_detection_segmentation/yolov4/dependencies/onnx-model-validation.ipynb
  vision/object_detection_segmentation/yolov4/model/yolov4.onnx
  vision/object_detection_segmentation/yolov4/model/yolov4.tar.gz
Labels: new-model

#331 YoloV4 - README update
  vision/object_detection_segmentation/yolov4/README.md
Labels: bug

#324 Added EfficientNet-Lite 4
  README.md
  vision/classification/efficientnet-lite4/README.md
  vision/classification/efficientnet-lite4/dependencies/labels_map.txt
  vision/classification/efficientnet-lite4/model/efficientnet-lite4.onnx
  vision/classification/efficientnet-lite4/model/efficientnet-lite4.tar.gz
Labels: new-model

#307 Model Zoo CI
  .azure-pipelines/MZoo-CI-Linux.yml
  .azure-pipelines/MZoo-CI-Windows.yml
  .azure-pipelines/test_models.py
  README.md
Labels: enhancement

#337 Fix data for Super Resolution model
  vision/super_resolution/sub_pixel_cnn_2016/model/super-resolution-10.tar.gz
Labels: bug, enhancement

#333 GoogLenet Pre and post process
  vision/classification/inception_and_googlenet/googlenet/README.md
Labels: enhancement

#328 Add Ssd-mobilenetv1
  README.md
  vision/object_detection_segmentation/ssd-mobilenetv1/README.md
  vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_10.onnx
  vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_10.tar.gz
Labels: new-model

#345 Fix postprocessing code for EfficientNet
  vision/classification/efficientnet-lite4/README.md
  vision/classification/efficientnet-lite4/model/efficientnet-lite4.tar.gz
Labels: bug

#338 Add RoBERTa
  README.md
  text/machine_comprehension/roberta/README.md
  text/machine_comprehension/roberta/dependencies/roberta-sequence-classification-inference.ipynb
  text/machine_comprehension/roberta/dependencies/roberta-sequence-classification-validation.ipynb
  text/machine_comprehension/roberta/model/roberta-base-11.onnx
  text/machine_comprehension/roberta/model/roberta-base-11.tar.gz
  text/machine_comprehension/roberta/model/roberta-sequence-classification-9.onnx
  text/machine_comprehension/roberta/model/roberta-sequence-classification-9.tar.gz
Labels: new-model
